language: python

dist: xenial

stages:
  - linting

python:
  - "3.7"

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"  

install:
  - pip install poetry==1.0.0a2
  - mkdir -p /home/travis/.config/pypoetry
  - echo "[repositories]" > /home/travis/.config/pypoetry/config.toml
  - poetry config settings.virtualenvs.create false
  - poetry install -v

script:
  - pre-commit run --all-files