version: "2"
services:
  app:
    image: philiptrauner/homepage-app:latest
    volumes:
      - ${BLOG_PATH}:/app/blog:ro
    restart: always
    # Takes precedence over value in `.env`
    environment:
      - PT_PORT=5000
    env_file: .env

  web:
    image: philiptrauner/homepage-web:latest
    volumes:
      - ${BLOG_PATH}:/static/blog:ro
    ports:
      - ${PORT-80}:80
    links:
      - app:app
