[project]
name = "philip-trauner.me"
version = "0.1.0"
readme = "README.md"
description = ""
license = "MIT"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
Jinja2 = "^3.0.3"
requests = "^2.24"
sanic = "^25.12"
pygments = "^2.11.2"
rfeed = { git = "https://github.com/svpino/rfeed.git" }
beautifulsoup4 = "^4.9"
watchdog = "^6.0.0"
result = { git = "https://github.com/dbrgn/result.git" }
pydantic = {extras = ["email"], version = "^1.7.2"}
environs = "^15.0.0"
pymdown-extensions = "^8.0.1"
furl = "^2.1.0"
html5lib = "^1.1"

[tool.poetry.group.dev.dependencies]
mypy = "^0.910"
black = "^22.1.0"
pre-commit = "^2.4"
bandit = "^1.6"
flake8 = "^3.8"
types-requests = "^2.25.11"
types-Markdown = "^3.3.6"
