[tool.poetry]
name = "philip-trauner.me"
version = "0.1.0"
readme = "README.md"
description = ""
authors = ["Philip Trauner <philip.trauner@arztpraxis.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Jinja2 = "^2.10"
Meh = "^1.2"
requests = "^2.19"
Sanic = "^0.7.0"
spotipy = "^2.4"
mistune = "^0.8.3"
pygments = "^2.2"
watchdog3 = "^0.8.4"
rfeed = { git = "https://github.com/PhilipTrauner/rfeed.git" }
django-htmlmin = "^0.10.0"
urlpath = "^1.1"

[tool.poetry.dev-dependencies]